### ISSUE TITLE
can we use PPO for discrete action spaces ? 

### ISSUE THREAD

**Issue by shamanez** [takuseno/ppo#2]

**Comment by donamin** [comment]
No you can't. There are several good algorithms for discrete action spaces. You can find them for example in [OpenAI Baselines](https://github.com/openai/baselines).

**Comment by takuseno** [comment]
@shamanez Hi, I updated my codes. Please check my repository again!

**Comment by mmcelikok** [comment]
From the OpenAI Spinning-up Docs:
"PPO can be used for environments with either discrete or continuous action spaces."
