### ISSUE TITLE
Incorrect Surrogate Loss Equation

### ISSUE THREAD

**Issue by Supermaxman** [takuseno/ppo#3]
On the following line I believe you are clipping the surrogate loss incorrectly:

https://github.com/takuseno/ppo/blob/b3282aa1a22c9ee862b9c4b4ff56467a14fa8790/build_graph.py#L53

The equation from the PPO paper (https://arxiv.org/abs/1707.06347) (Equation 7) takes the minimum **after** multiplying by the advantages, while here you are taking the minimum **before** multiplying by the advantages. This changes the equation, as you are not taking the direction of the advantages into account. The paper specifically addresses the advantage direction as being integral to the clipping, where they say, "...note that the probability ratio r is clipped at 1 − epsilon or 1 + epsilon depending on whether the advantage is positive or negative." In your current implementation you are not always imposing clipping. 

Consider changing the line to the following:

```
tf.minimum(ratio * advantage_t_ph, clipped_ratio * advantage_t_ph),
```

**Comment by takuseno** [comment]
@Supermaxman hi, thank you for reading my code!! Your point is definitely correct. I'll fix that. I appreciate your advice!!

**Comment by takuseno** [comment]
I've fixed it. See https://github.com/takuseno/ppo/commit/a4fbd383f0f89ce2d881a8b78d6b8a03294e5c7c .
